version: "3.8"
services:
  web:
    build: .
    expose:
      - "3000"
    deploy:
      replicas: 3
    restart: always
    networks:
      - app_network
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
